# Generated by Django 5.2 on 2025-04-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0002_curso_documento'),
        ('usuario', '0003_rename_curso_desejado_informacoespessoais_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('alunos', models.ManyToManyField(blank=True, to='usuario.informacoespessoais')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instsoli.curso')),
            ],
        ),
    ]
