# Generated by Django 5.1.6 on 2025-04-21 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0004_remove_turma_descricao'),
        ('usuario', '0004_alter_informacoespessoais_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('presente', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.informacoespessoais')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instsoli.turma')),
            ],
            options={
                'unique_together': {('turma', 'aluno', 'data')},
            },
        ),
    ]
