# Generated by Django 5.2 on 2025-04-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0005_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
