# Generated by Django 5.2 on 2025-05-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0008_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='solucao_resposta',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='mensagem',
            field=models.TextField(default=''),
        ),
    ]
