# Generated by Django 5.2 on 2025-05-18 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0010_solicitacao_arquivada'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemestreAvaliativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aprovado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprovados', to='instsoli.semestreavaliativo')),
            ],
        ),
    ]
