# Generated by Django 5.2 on 2025-05-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0011_semestreavaliativo_aprovado'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestreavaliativo',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='instsoli.curso'),
        ),
    ]
