# Generated by Django 5.1.6 on 2025-04-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoespessoais',
            name='escolaridade',
            field=models.CharField(choices=[('npe', 'Não possuo escolaridade'), ('fi', 'Fundamental Incompleto'), ('fc', 'Fundamental Completo'), ('emi', 'Ensino Médio Incompleto'), ('emc', 'Ensino Médio Completo'), ('esi', 'Ensino Superior Incompleto'), ('esc', 'Ensino Superior Completo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('pni', 'Prefiro não informar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='informacoespessoais',
            name='turno',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=50),
        ),
    ]
