# Generated by Django 5.1.6 on 2025-04-18 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_informacoespessoais_escolaridade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacoespessoais',
            old_name='curso_desejado',
            new_name='curso',
        ),
    ]
