# Generated by Django 5.1.6 on 2025-04-20 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instsoli', '0004_remove_turma_descricao'),
        ('usuario', '0003_rename_curso_desejado_informacoespessoais_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoespessoais',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instsoli.curso'),
        ),
    ]
