# Generated by Django 5.2 on 2025-04-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_informacoespessoais_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacoespessoais',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
